### ISSUE TITLE
Reduce Database Hits

### ISSUE THREAD

**Issue by SillyInventor** [CSDTs/django_teams#10]
@serenasyw I can't assign this to you yet because I only added you to that specific repo *head desk* back at any rate, I'd like it if you could go through and reduce the number of database hits for each of the pages in this repo.

**Comment by serenasyw** [comment]
Ok. Is there a way to test on the number of database hits?

2018-02-21 10:24 GMT-05:00 Silly Inventor <notifications@github.com>:

**Comment by SillyInventor** [comment]
Yes, many. My preferred method is:
https://django-debug-toolbar.readthedocs.io/en/stable/

**Comment by serenasyw** [comment]
The toolbar is working now. It seems like I have to login to get pages like
/myteams working.. right now I could only view /teams but there is no data
on it.

2018-02-22 11:30 GMT-05:00 Silly Inventor <notifications@github.com>:

**Comment by serenasyw** [comment]
I have pushed my updates to the repo, but I am still very confused
actually.. there is only 1 query for the teams page, so I don't know how to
test my updates on that.

2018-02-24 15:02 GMT-05:00 Yawen Shen <yawen.shen620@gmail.com>:

**Comment by SillyInventor** [comment]
I recommend, installing and setting up the toolbar. Pick a page, probably the main list page, then add a bunch of example items to the dataset (empty classrooms, etc) and then look at the toolbar number of hits. Then ID the problem with the query setup, and fix it. It is decidedly not O(1).

**Comment by SillyInventor** [comment]
Yay!
