### ISSUE TITLE
Detail view selection bugs

### ISSUE THREAD

**Issue by SillyInventor** [CSDTs/django_teams#15]
After the update, there are a few bugs as found on the dev site.
https://dev.csdt.rpi.edu/teams/teams/94/

the projects shouldn't have little bars at the top.
![image](https://user-images.githubusercontent.com/8440451/38693291-72f0971a-3e54-11e8-941c-0d5d6bdaf6bd.png)

**Comment by serenasyw** [comment]
I added some approved objects but I couldn't replicate this bug on my laptop.. Could it be a problem with the template?

**Comment by SillyInventor** [comment]
I fixed this. In a recent set of commits.
